routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {

    return view('home');
});
Route::view('/api-docs', 'Docs.index');
Route::get('/webadmin/login', 'Auth\LoginController@showLoginForm');



Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/degrees', 'admin\DegreeController');
    Route::resource('/countries', 'admin\CountriesController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/questions', 'admin\QuestionsController');
    Route::resource('/question/{id}/answers', 'admin\AnswersController');
    Route::resource('/answer/{id}/replies', 'admin\RepliesController');
    Route::resource('/reports', 'admin\ReportsController');
    Route::get('/admins/{id}/admin', 'admin\AdminsController@admin');
    Route::get('/users/{id}/ban', 'admin\UsersController@ban');
    Route::get('/settings/edit', 'admin\SettingsController@edit');
    Route::post('/settings/update', 'admin\SettingsController@update');



});
Route::get('/getcode', function () {
    $video_id = Input::get('video_id');
    $code = Input::get('code');
    $code=\App\Models\Video_code::where('video_id',$video_id)->where('code',$code)->first();

    return response()->json($code);

});

app/User.php
<?php

namespace App;


use App\Models\Answer;
use App\Models\City;
use App\Models\Country;
use App\Models\educationDegree;
use App\Models\Message;
use App\Models\Question;
use App\Models\Reply;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;


class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    protected $dates = ['deleted_at'];


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
//    protected $fillable = [
//        'name', 'email', 'password','role','phone','photo'
//    ];
    protected $guarded=[];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function country()
    {
        return $this->belongsTo(Country::class, 'country_id');
    }
    public function city()

    {
        return $this->belongsTo(City::class, 'city_id');
    }
    public function educationDegree()

    {
        return $this->belongsTo(educationDegree::class, 'educationDegree_id');
    }
    public function questions()

    {
        return $this->hasMany(Question::class, 'user_id');
    }
    public function answers()

    {
        return $this->hasMany(Answer::class, 'user_id');
    }
    public function replies()

    {
        return $this->hasMany(Reply::class, 'user_id');
    }
    public function receivedMessages()
    {
        return $this->hasMany(Message::class, 'receiver_id');
    }
}

app/Http/Controllers/admin/UsersController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\BankData;
use App\Models\CarOrder;
use App\Models\MobileData;
use App\Models\PropertyOrder;
use App\Models\Transfer;
use App\Notifications\BookingRequestReceived;
use App\Notifications\FromAdmin;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Notification;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=User::where('role',0)->withTrashed()->get();

        return view('admin.users.index',compact('users'));
    }
    public function ban($id){
        $user=User::withTrashed()->where('id',$id)->first();
        if ($user->ban==0)
        {
            $user->ban = 1;
            $user->save();

            return redirect('/webadmin/users')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم الحظر بنجاح']));
        }else{
            $user->ban = 0;
            $user->save();
            return redirect('webadmin/users')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم فك الحظر بنجاح']));


        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'fullName' => 'required',
            'userName' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required',
        ]);
        $user=User::create([
            'fullName' => $request->fullName,
            'userName' => $request->userName,
            'email' => $request->email,
            'token'=>bin2hex(random_bytes(20)),
            'password' => Hash::make($request->password),
        ]);
        if ($request->hasFile('photo')) {
            $request->validate([

                'photo' => 'image|mimes:jpeg,png,jpg,gif,svg'

            ]);

            $imageName = str_random(10).'.'.$request->file('photo')->extension();
            $request->file('photo')->move(
                base_path() . '/public/uploads/profiles/', $imageName
            );
            $user->photo ='/uploads/profiles/'. $imageName;
            $user->save();

        }


        return redirect('/webadmin/users')->withFlashMessage(json_encode(['success'=>true,'msg'=>'User Added Successfully']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user=User::withTrashed()->where('id',$id)->first();
        return view('admin.users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user=User::withTrashed()->where('id',$id)->first();
        return view('admin.users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'fullName' => 'required',
            'userName' => 'required',

        ]);
        $user=User::withTrashed()->where('id',$id)->first();
        $user->update([
            'fullName'=>$request->fullName,
            'userName'=>$request->userName,
        ]);
        if ($request->email !=$user->email)
        {
            $this->validate($request, [
                'email' => 'email|unique:users',
            ]);
            $user->update([
                'email'=>$request->email
            ]);

        }
        if ($request->password !=''){
            $user->update([
                'password'=>Hash::make($request->password),
            ]);
        }
        if ($request->hasFile('photo')) {
            $request->validate([

                'photo' => 'image|mimes:jpeg,png,jpg,gif,svg'

            ]);

            $imageName = str_random(10).'.'.$request->file('photo')->extension();
            $request->file('photo')->move(
                base_path() . '/public/uploads/profiles/', $imageName
            );
            $user->photo ='/uploads/profiles/'. $imageName;
            $user->save();

        }

        return redirect('/webadmin/users')->withFlashMessage(json_encode(['success'=>true,'msg'=>'User Edited Successfully']));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User::where('id',$id)->first();

        $user->delete();
        return redirect()->back()->withFlashMessage(json_encode(['success'=>true,'msg'=>'User Deleted Successfully']));
    }


}

resources/views/admin/users/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة عضو
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/users')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاعضاء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">اضافة عضو</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')



@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       اضافة عضو
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/users" method="post" enctype="multipart/form-data" >
            <div class="m-portlet__body">
                @csrf
                @include('admin.users.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')


@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('title')
   تعديل عضو
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/users')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاعضاء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تعديل عضو</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل عضو
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($user,['route' => ['users.update' , $user->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">

            @include('admin.users.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/users/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">الاسم: </label>
    <div class="col-lg-10{{ $errors->has('fullName') ? ' has-danger' : '' }}">
        {!! Form::text('fullName',old('fullName'),['class'=>'form-control m-input','autofocus','placeholder'=> 'الاسم ' ]) !!}
        @if ($errors->has('fullName'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('fullName') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">اسم المستخدم: </label>
    <div class="col-lg-10{{ $errors->has('userName') ? ' has-danger' : '' }}">
        {!! Form::text('userName',old('userName'),['class'=>'form-control m-input','placeholder'=> 'اسم المستخدم' ]) !!}
        @if ($errors->has('userName'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('userName') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">البريد الالكترونى: </label>
    <div class="col-lg-10{{ $errors->has('email') ? ' has-danger' : '' }}">
        {!! Form::text('email',old('email'),['class'=>'form-control m-input','placeholder'=> 'البريد الالكترونى' ]) !!}
        @if ($errors->has('email'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">كلمة المرور: </label>
    <div class="col-lg-10{{ $errors->has('password') ? ' has-danger' : '' }}">
        {!! Form::password('password',['class'=>'form-control m-input','placeholder'=> 'كلمة المرور' ]) !!}
        @if ($errors->has('password'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('password') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">صورة الملف الشخصى: </label>
    <div class="col-lg-10{{ $errors->has('photo') ? ' has-danger' : '' }}">

        <input type="file" name="photo"   class="form-control uploadinput">
        @if ($errors->has('photo'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('photo') }}</strong>
            </span>
        @endif
    </div>

</div>
@if(isset($user) && $user->photo)
<div class="row">




            <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

                <img
                        data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                        alt="First slide [800x4a00]"
                        src="{{$user->photo}}"
                        style="height: 150px; width: 150px"
                        data-holder-rendered="true">
            </div>

</div>
@endif

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')
@section('title')
   الاعضاء
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/users')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاعضاء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        الاعضاء
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('users.create')}}" style="margin-bottom:20px;background-color: #00a3b6" class="btn btn_primary " ><i class=" fa fa-edit"></i>اضافة عضو</a></div>




            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result" id="m_table_testArea">

                <thead>
                <tr>
                    <th>#</th>
                    <th>الاسم</th>
                    <th>اسم المستخدم</th>
                    <th>البريد الالكتروني</th>
                    <th>الحاله</th>
                    <th>الادوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $index=> $user)

                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$user->fullName}} </td>
                        <td>{{$user->userName}} </td>
                        <td>{{$user->email}} </td>
                        <td>{{$user->ban==0?'نشط':'محظور'}} </td>
                        <td>
{{--                            {{$user->can_rent && $user->national_id!=null ? 'Verified':'Waiting For Verify'}}--}}
                            {{--@if($user->can_rent && $user->national_id)--}}
                                {{--{{'Verified'}}--}}
                            {{--@endif--}}
                            {{--@if(!$user->can_rent && $user->national_id)--}}
                                {{--{{'Wating For Verify'}}--}}
                            {{--@endif--}}
                            {{--@if(!$user->can_rent && !$user->national_id)--}}
                                {{--{{'Unverified'}}--}}
                            {{--@endif--}}

                        </td>

                        <td>
                            @if($user->role==0)
                                <a  title="اجعله مدير" href="/webadmin/admins/{{$user->id}}/admin" ><i class="fa fa-user-alt"></i></a>
                            @else
                                <a  title="اجعله عضو عادى" href="/webadmin/admins/{{$user->id}}/admin" ><i class="fa fa-user"></i></a>
                            @endif

                            @if($user->ban==0)
                                <a  title="حظر" href="/webadmin/users/{{$user->id}}/ban" ><i class="fa fa-ban"></i></a>
                            @else
                                <a  title="فك الحظر" href="/webadmin/users/{{$user->id}}/ban" ><i class="fa fa-check-circle"></i></a>
                            @endif

                            <a  title="عرض"   href="/webadmin/users/{{$user->id}}" ><i class="fa fa-eye"></i></a>
                            {{--<a  title="Bank Data" href="/webadmin/user/{{$user->id}}/bank-data" ><i class="fa fa-credit-card"></i></a>--}}
                            <a  title="تعديل" href="/webadmin/users/{{$user->id}}/edit" ><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/users/{{ $user->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete" />
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}

@endsection

resources/views/admin/users/send-notification.blade.php
@extends('admin.layouts.app')

@section('title')
    Send Notification
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/users')}}" class="m-menu__link">
            <span class="m-menu__link-text">Users</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">Send Notification</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        Send Notification
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/store-notification" method="post" enctype="multipart/form-data" >
            <div class="m-portlet__body">
                @csrf
                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label">User : </label>
                    <div class="col-lg-10{{ $errors->has('user_id') ? ' has-danger' : '' }}">
                        <select name="user_id[]" data-placeholder="User" class="form-control  " multiple >
                            <option >select users</option>
                            <option value="all" >All Users</option>

                                @foreach($users as $user)
                                    <option value="{{$user->id}}" >{{$user->email}} </option>
                                @endforeach



                        </select>
                        @if ($errors->has('user_id'))
                            <span class="form-control-feedback" role="alert">
                                <strong>{{ $errors->first('user_id') }}</strong>
                            </span>
                        @endif
                    </div>

                </div>
                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label">Message Iin Arabic : </label>
                    <div class="col-lg-10{{ $errors->has('ar_message') ? ' has-danger' : '' }}">
                        <input class="form-control m-input" name="ar_message" value="" >
                        @if ($errors->has('ar_message'))
                            <span class="form-control-feedback" role="alert">
                                <strong>{{ $errors->first('ar_message') }}</strong>
                            </span>
                        @endif
                    </div>

                </div>
                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label">Message In English : </label>
                    <div class="col-lg-10{{ $errors->has('en_message') ? ' has-danger' : '' }}">
                        <input class="form-control m-input" name="en_message" value="" >
                        @if ($errors->has('en_message'))
                            <span class="form-control-feedback" role="alert">
                                <strong>{{ $errors->first('en_message') }}</strong>
                            </span>
                        @endif
                    </div>

                </div>

            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">Send</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/users/show.blade.php
@extends('admin.layouts.app')

@section('title')
     تفاصيل عضو
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/users')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاعضاء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تفاصيل عضو</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       تفاصيل عضو
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($user,['route' => ['users.show' , $user->id],'method'=> 'get','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">

{{--            @include('admin.users.form')--}}

            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">الاسم: </label>
                <div class="col-lg-10{{ $errors->has('f_name') ? ' has-danger' : '' }}">
                    {!! Form::text('fullName',old('fullName'),['class'=>'form-control m-input','autofocus','disabled','placeholder'=> 'الاسم' ]) !!}

                </div>

            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">اسم المستخدم: </label>
                <div class="col-lg-10{{ $errors->has('l_name') ? ' has-danger' : '' }}">
                    {!! Form::text('userName',old('userName'),['class'=>'form-control m-input','disabled','placeholder'=> 'اسم المستخدم' ]) !!}

                </div>

            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">البريد الالكتروني: </label>
                <div class="col-lg-10{{ $errors->has('email') ? ' has-danger' : '' }}">
                    {!! Form::text('email',old('email'),['class'=>'form-control m-input','disabled','placeholder'=> 'البريد الالكترونى' ]) !!}
                    @if ($errors->has('email'))
                        <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
                    @endif
                </div>

            </div>
            @if($user->photo)
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Profile Picture: </label>
                <div class="col-lg-10{{ $errors->has('photo') ? ' has-danger' : '' }}">
                    <img
                            data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                            alt=""
                            src="{{$user->photo}}"
                            style="height: 150px; width: 150px"
                            data-holder-rendered="true">


                </div>

            </div>
            @endif






        </div>

    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection