routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {

    return view('home');
});
Route::view('/api-docs', 'Docs.index');
Route::get('/webadmin/login', 'Auth\LoginController@showLoginForm');



Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/degrees', 'admin\DegreeController');
    Route::resource('/countries', 'admin\CountriesController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/questions', 'admin\QuestionsController');
    Route::resource('/question/{id}/answers', 'admin\AnswersController');
    Route::resource('/answer/{id}/replies', 'admin\RepliesController');
    Route::resource('/reports', 'admin\ReportsController');
    Route::get('/admins/{id}/admin', 'admin\AdminsController@admin');
    Route::get('/users/{id}/ban', 'admin\UsersController@ban');
    Route::get('/settings/edit', 'admin\SettingsController@edit');
    Route::post('/settings/update', 'admin\SettingsController@update');



});
Route::get('/getcode', function () {
    $video_id = Input::get('video_id');
    $code = Input::get('code');
    $code=\App\Models\Video_code::where('video_id',$video_id)->where('code',$code)->first();

    return response()->json($code);

});

resources/views/admin/admins/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة مدير
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/admins')}}" class="m-menu__link">
            <span class="m-menu__link-text">المدراء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">اضافة مدير</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')



@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       اضافة مدير
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/admins" method="post" enctype="multipart/form-data" >
            <div class="m-portlet__body">
                @csrf
                @include('admin.admins.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')


@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.app')

@section('title')
   تعديل مدير
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/admins')}}" class="m-menu__link">
            <span class="m-menu__link-text">المدراء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تعديل مدير</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل مدير
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($admin,['route' => ['admins.update' , $admin->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">

            @include('admin.admins.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/admins/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">الاسم: </label>
    <div class="col-lg-10{{ $errors->has('fullName') ? ' has-danger' : '' }}">
        {!! Form::text('fullName',old('fullName'),['class'=>'form-control m-input','autofocus','placeholder'=> 'الاسم ' ]) !!}
        @if ($errors->has('fullName'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('fullName') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">اسم المستخدم: </label>
    <div class="col-lg-10{{ $errors->has('userName') ? ' has-danger' : '' }}">
        {!! Form::text('userName',old('userName'),['class'=>'form-control m-input','placeholder'=> 'اسم المستخدم' ]) !!}
        @if ($errors->has('userName'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('userName') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">البريد الالكترونى: </label>
    <div class="col-lg-10{{ $errors->has('email') ? ' has-danger' : '' }}">
        {!! Form::text('email',old('email'),['class'=>'form-control m-input','placeholder'=> 'البريد الالكترونى' ]) !!}
        @if ($errors->has('email'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">كلمة المرور: </label>
    <div class="col-lg-10{{ $errors->has('password') ? ' has-danger' : '' }}">
        {!! Form::password('password',['class'=>'form-control m-input','placeholder'=> 'كلمة المرور' ]) !!}
        @if ($errors->has('password'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('password') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">صورة الملف الشخصى: </label>
    <div class="col-lg-10{{ $errors->has('photo') ? ' has-danger' : '' }}">

        <input type="file" name="photo"   class="form-control uploadinput">
        @if ($errors->has('photo'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('photo') }}</strong>
            </span>
        @endif
    </div>

</div>
@if(isset($admin) && $admin->photo)
<div class="row">




            <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

                <img
                        data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                        alt="First slide [800x4a00]"
                        src="{{$admin->photo}}"
                        style="height: 150px; width: 150px"
                        data-holder-rendered="true">
            </div>

</div>
@endif

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.app')
@section('title')
   المدراء
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/admins')}}" class="m-menu__link">
            <span class="m-menu__link-text">المدراء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        المدراء
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('admins.create')}}" style="margin-bottom:20px;background-color: #00a3b6"  class="btn btn_primary " ><i class=" fa fa-edit"></i>اضافة مدير</a></div>




            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result" id="m_table_testArea">

                <thead>
                <tr>
                    <th>#</th>
                    <th>الاسم</th>
                    <th>اسم المستخدم</th>
                    <th>البريد الالكترونى</th>
                    <th>الحاله</th>
                    <th>الادوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($admins as $index=> $admin)

                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$admin->fullName}} </td>
                        <td>{{$admin->userName}} </td>
                        <td>{{$admin->email}} </td>
{{--                        <td>{{$user->phone}} </td>--}}
                        <td>
{{--                            {{$user->can_rent && $user->national_id!=null ? 'Verified':'Waiting For Verify'}}--}}
                            {{--@if($user->can_rent && $user->national_id)--}}
                                {{--{{'Verified'}}--}}
                            {{--@endif--}}
                            {{--@if(!$user->can_rent && $user->national_id)--}}
                                {{--{{'Wating For Verify'}}--}}
                            {{--@endif--}}
                            {{--@if(!$user->can_rent && !$user->national_id)--}}
                                {{--{{'Unverified'}}--}}
                            {{--@endif--}}

                        </td>

                        <td>
                            @if($admin->role==0)
                            <a  title="اجعله مدير" href="/webadmin/admins/{{$admin->id}}/admin" ><i class="fa fa-user-alt"></i></a>
                            @else
                            <a  title="اجعله عضو عادى" href="/webadmin/admins/{{$admin->id}}/admin" ><i class="fa fa-user"></i></a>
                            @endif

                            {{--<a  title="عرض"   href="/webadmin/admins/{{$admin->id}}" ><i class="fa fa-eye"></i></a>--}}
                            {{--<a  title="Bank Data" href="/webadmin/user/{{$user->id}}/bank-data" ><i class="fa fa-credit-card"></i></a>--}}
                            <a  title="تعديل" href="/webadmin/admins/{{$admin->id}}/edit" ><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/admins/{{ $admin->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete" />
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}

@endsection