routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {

    return view('home');
});
Route::view('/api-docs', 'Docs.index');
Route::get('/webadmin/login', 'Auth\LoginController@showLoginForm');



Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/degrees', 'admin\DegreeController');
    Route::resource('/countries', 'admin\CountriesController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/questions', 'admin\QuestionsController');
    Route::resource('/question/{id}/answers', 'admin\AnswersController');
    Route::resource('/answer/{id}/replies', 'admin\RepliesController');
    Route::resource('/reports', 'admin\ReportsController');
    Route::get('/admins/{id}/admin', 'admin\AdminsController@admin');
    Route::get('/users/{id}/ban', 'admin\UsersController@ban');
    Route::get('/settings/edit', 'admin\SettingsController@edit');
    Route::post('/settings/update', 'admin\SettingsController@update');



});
Route::get('/getcode', function () {
    $video_id = Input::get('video_id');
    $code = Input::get('code');
    $code=\App\Models\Video_code::where('video_id',$video_id)->where('code',$code)->first();

    return response()->json($code);

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table='categories';
    protected $guarded=[];
}

app/Http/Controllers/admin/CategoriesController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories=Category::all();

        return view('admin.categories.index',compact('categories'));
    }
    public function getSearchResult($status){
        if ($status==1){//verified
            $users=User::where('role',0)->where('can_rent',1)->where('national_id','<>',null)->withTrashed()->get();
        }
        if ($status==2){//waiting for verify
            $users=User::where('role',0)->where('can_rent',0)->where('national_id','<>',null)->withTrashed()->get();
        }
        if ($status==3){//unverified
            $users=User::where('role',0)->where('can_rent',0)->where('national_id',null)->withTrashed()->get();
        }
        $users->transform(function($i)  {
            $transfers=Transfer::where('user_id',$i->id)->sum('amount');
            $i->transfers=$transfers;
            return $i;


        });
        return response()->json($users);


    }
    public function verify($id){
        $user=User::withTrashed()->where('id',$id)->first();
        if ($user->can_rent==0)
        {
            $user->can_rent = 1;
            $user->save();
            $carOrders = CarOrder::where('status', 'Pending Verify')->where('user_id', $id)->get();
            $propertyOrders = PropertyOrder::where('status', 'Pending Verify')->where('user_id', $id)->get();
            foreach ($carOrders as $order) {
                $order->update(['status' => 'Requested']);
                $provider = $order->car->user;
                $data = [
                    'user' => $user,
                    'type' => 1
                ];

                Mail::send('emails.newBooking', $data, function ($message) use ($provider) {
                    $message->from('postmaster@renzo.app', 'renzo')
                        ->to($provider->email)
                        ->subject('Booking, renzo App');
                });
                //provider notification
                if ($provider->notifiable) {
                    $ar_message = 'لديك طلب جديد لاستئجار سيارتك';
                    $en_message = 'You have a new request to rent your car';
                    Notification::send($provider, new BookingRequestReceived($ar_message, $en_message, 1, $order->car->id));
                    $phone_datas = MobileData::where('user_id', $provider->id)
                        ->get(); // user who receive notification
                    $ar_title = 'حجز جديد';
                    $en_title = 'Booking Request';
                    $en_arr = [
                        'title' => 'Booking Request',
                        'body' => $en_message,
                        'sound' => 'default',
                        'type' => 1,
                        'ref_id' => $order->car->id,
                        'note_type' => 'BookingRequestReceived',
                        'content_available' => true,
                        'priority' => 'high'
                    ];
                    $ar_arr = [
                        'title' => 'حجز جديد',
                        'body' => $ar_message,
                        'sound' => 'default',
                        'type' => 1,
                        'ref_id' => $order->car->id,
                        'note_type' => 'BookingRequestReceived',
                        'content_available' => true,
                        'priority' => 'high'
                    ];
                    foreach ($phone_datas as $phone_data) {
                        if ($provider->current_language == 'ar')
                            Firebase_notifications_fcm($phone_data->mobile_token, $ar_title, $ar_message, $ar_arr);
                        if ($provider->current_language == 'en')
                            Firebase_notifications_fcm($phone_data->mobile_token, $en_title, $en_message, $en_arr);


                    }
                }


            }
            foreach ($propertyOrders as $order) {
                $order->update(['status' => 'Requested']);

                $provider = $order->property->user;
                $data = [
                    'user' => $user,
                    'type' => 2
                ];

                Mail::send('emails.newBooking', $data, function ($message) use ($provider) {
                    $message->from('postmaster@renzo.app', 'renzo')
                        ->to($provider->email)
                        ->subject('Booking, renzo App');
                });
                //notification
                if ($provider->notifiable) {
                    $ar_message = 'لديك طلب جديد لاستئجار عقارك';
                    $en_message = 'You have a new request to rent your property';
                    Notification::send($provider, new BookingRequestReceived($ar_message, $en_message, 2, $order->property->id));
                    $phone_datas = MobileData::where('user_id', $provider->id)
                        ->get(); // user who receive notification
                    $ar_title = 'حجز جديد';
                    $en_title = 'Booking Request';
                    $en_arr = [
                        'title' => 'Booking Request',
                        'body' => $en_message,
                        'sound' => 'default',
                        'type' => 2,
                        'ref_id' => $order->property->id,
                        'note_type' => 'BookingRequestReceived',
                        'content_available' => true,
                        'priority' => 'high'
                    ];
                    $ar_arr = [
                        'title' => 'حجز جديد',
                        'body' => $ar_message,
                        'sound' => 'default',
                        'type' => 2,
                        'ref_id' => $order->property->id,
                        'note_type' => 'BookingRequestReceived',
                        'content_available' => true,
                        'priority' => 'high'
                    ];
                    foreach ($phone_datas as $phone_data) {
                        if ($provider->current_language == 'ar')
                            Firebase_notifications_fcm($phone_data->mobile_token, $ar_title, $ar_message, $ar_arr);
                        if ($provider->current_language == 'en')
                            Firebase_notifications_fcm($phone_data->mobile_token, $en_title, $en_message, $en_arr);


                    }
                }


            }


            return redirect()->back()->withFlashMessage(json_encode(['success' => true, 'msg' => 'User Verified, Can Rent Now']));
        }else{
            $user->can_rent = 0;
            $user->save();
            return redirect()->back()->withFlashMessage(json_encode(['success' => true, 'msg' => 'Verify Removed Successfully']));


        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'name' => 'required',
            'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg'
        ]);


        $imageName = str_random(10).'.'.$request->file('photo')->extension();
        $request->file('photo')->move(
            base_path() . '/public/uploads/categories/', $imageName
        );

       Category::create([
            'name' => $request->name,
            'photo' => '/uploads/categories/'. $imageName,
        ]);



        return redirect('/webadmin/categories')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم اضافة القسم بنجاح']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category=Category::where('id',$id)->first();
        return view('admin.categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $category=Category::where('id',$id)->first();

        if ($request->name !=$category->name)
        {

            $category->update([
                'name'=>$request->name
            ]);

        }

        if ($request->hasFile('photo')) {
            $request->validate([

                'photo' => 'image|mimes:jpeg,png,jpg,gif,svg'

            ]);

            $imageName = str_random(10).'.'.$request->file('photo')->extension();
            $request->file('photo')->move(
                base_path() . '/public/uploads/categories/', $imageName
            );
            $category->photo ='/uploads/categories/'. $imageName;
            $category->save();

        }

        return redirect('/webadmin/categories')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم التعديل بنجاح']));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category=Category::where('id',$id)->first();

        $category->delete();
        return redirect()->back()->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم الحذف بنجاح']));
    }
}

resources/views/admin/categories/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة قسم
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/categories')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاقسام</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">اضافة قسم</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')



@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       اضافة قسم
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/categories" method="post" enctype="multipart/form-data" >
            <div class="m-portlet__body">
                @csrf
                @include('admin.categories.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')


@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('title')
   تعديل قسم
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/categories')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاقسام</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تعديل قسم</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل قسم
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($category,['route' => ['categories.update' , $category->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">

            @include('admin.categories.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/categories/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">الاسم: </label>
    <div class="col-lg-10{{ $errors->has('name') ? ' has-danger' : '' }}">
        {!! Form::text('name',old('name'),['class'=>'form-control m-input','autofocus','placeholder'=> 'الاسم ' ]) !!}
        @if ($errors->has('name'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>

</div>

<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">الصورة : </label>
    <div class="col-lg-10{{ $errors->has('photo') ? ' has-danger' : '' }}">

        <input type="file" name="photo"   class="form-control uploadinput">
        @if ($errors->has('photo'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('photo') }}</strong>
            </span>
        @endif
    </div>

</div>
@if(isset($category) && $category->photo)
<div class="row">




            <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

                <img
                        data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                        alt="First slide [800x4a00]"
                        src="{{$category->photo}}"
                        style="height: 150px; width: 150px"
                        data-holder-rendered="true">
            </div>

</div>
@endif

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title')
   الاقسام
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/categories')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاقسام</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        الاقسام
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('categories.create')}}" style="margin-bottom:20px;background-color: #00a3b6" class="btn btn_primary " ><i class=" fa fa-edit"></i>اضافة قسم</a></div>




            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result" id="m_table_testArea">

                <thead>
                <tr>
                    <th>#</th>
                    <th>الاسم</th>
                    <th>الصورة</th>
                    <th>الادوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $index=> $category)

                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$category->name}} </td>
                        <td><img src="{{$category->photo}}" width="90px;" height="90px;"> </td>


                        <td>


                            <a  title="تعديل" href="/webadmin/categories/{{$category->id}}/edit" ><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/categories/{{ $category->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete" />
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}

@endsection