routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {

    return view('home');
});
Route::view('/api-docs', 'Docs.index');
Route::get('/webadmin/login', 'Auth\LoginController@showLoginForm');



Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/degrees', 'admin\DegreeController');
    Route::resource('/countries', 'admin\CountriesController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/questions', 'admin\QuestionsController');
    Route::resource('/question/{id}/answers', 'admin\AnswersController');
    Route::resource('/answer/{id}/replies', 'admin\RepliesController');
    Route::resource('/reports', 'admin\ReportsController');
    Route::get('/admins/{id}/admin', 'admin\AdminsController@admin');
    Route::get('/users/{id}/ban', 'admin\UsersController@ban');
    Route::get('/settings/edit', 'admin\SettingsController@edit');
    Route::post('/settings/update', 'admin\SettingsController@update');



});
Route::get('/getcode', function () {
    $video_id = Input::get('video_id');
    $code = Input::get('code');
    $code=\App\Models\Video_code::where('video_id',$video_id)->where('code',$code)->first();

    return response()->json($code);

});

app/Models/Answer.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $table='questionAnswers';
    protected $guarded=[];
    public function question()

    {
        return $this->belongsTo(Question::class, 'question_id');
    }
    public function user()

    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/admin/AnswersController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AnswersController extends Controller
{
    public function index($question_id)
    {
        $question=Question::find($question_id);
        $answers=Answer::where('question_id',$question_id)->get();

        return view('admin.answers.index',compact('answers','question'));
    }
    public function show($question_id,$id)
    {
        $question=Question::find($question_id);
        $answer=Answer::find($id);

        return view('admin.answers.show',compact('question','answer'));
    }
    public function destroy($question_id,$id)
    {
        $answer=Answer::where('id',$id)->first();

        $answer->delete();
        return redirect()->back()->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم الحذف بنجاح']));
    }
}

resources/views/admin/answers/index.blade.php
@extends('admin.layouts.app')
@section('title')
   الاجوبة
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/questions')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاسئلة</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        الاجوبة
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            {{--<div><a href="{{route('reports.create')}}" style="margin-bottom:20px" class="btn btn_primary btn btn-danger" ><i class=" fa fa-edit"></i>اضافة عضو</a></div>--}}




            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result" id="m_table_testArea">

                <thead>
                <tr>
                    <th>#</th>
                    <th>العضو صاحب الاجابة</th>
                    <th>الاجابة</th>
                    <th>الادوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($answers as $index=> $answer)

                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$answer->user->fullName}} </td>
                        <td>{{$answer->answerText}}</td>


                        <td>


                            <a  title="عرض"   href="/webadmin/question/{{$question->id}}/answers/{{$answer->id}}" ><i class="fa fa-eye"></i></a>
                            <a  title="الردود"   href="/webadmin/answer/{{$answer->id}}/replies" ><i class="fa fa-reply"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/question/{{ $question->id }}/answers/{{$answer->id}}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete" />
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}

@endsection

resources/views/admin/answers/show.blade.php
@extends('admin.layouts.app')

@section('title')
     تفاصيل الاجابة
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Home</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/question'.$question->id.'/answers')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاجوبه</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تفاصيل الاجابة</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       تفاصيل الاجابة
                    </h3>
                </div>
            </div>
        </div>
        <form method="get" action="/webadmin/question/{{$question->id}}/answers/{{$answer->id}}" class="m-form m-form--fit m-form--label-align-right">
        <!--begin::Form-->
{{--        {!! Form::model($answer,['route' => ['answers.show' , $answer->id],'method'=> 'get','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}--}}
        <div class="m-portlet__body">


            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">الاجابة: </label>
                <div class="col-lg-10{{ $errors->has('f_name') ? ' has-danger' : '' }}">
{{--                    {!! Form::text('fullName',old('fullName'),['class'=>'form-control m-input','autofocus','disabled','placeholder'=> 'الاسم' ]) !!}--}}
                    <textarea class="form-control m-input" disabled >{{$answer->answerText}}</textarea>

                </div>

            </div>
            @if($answer->photo)
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">الصوره: </label>
                <div class="col-lg-10{{ $errors->has('f_name') ? ' has-danger' : '' }}">
                    <img src="{{$answer->photo}}" width="150px" height="150px">

                </div>

            </div>
            @endif







        </div>
    </form>

{{--    {!! Form::close() !!}--}}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection